name: ai_client
description: Abstract interface for AI clients
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
